In [2]:
#矩阵的加减
import numpy as np

A = np.array([[1,2,3], [4,5,6]])
B = np.array([[6,5,4], [3,2,1]])

#加法
C = A + B
print("A+B",C)
C = A * B
print("A*B",C)

A+B [[7 7 7]
 [7 7 7]]
A*B [[ 6 10 12]
 [12 10  6]]


In [5]:
#矩阵乘法
A = np.array([[1,2], [4,5]])
B = np.array([[2,3], [5,6]])

print(A @ B) # 1*4 + 2 * 4

print("====================")
print(B @ A)

[[12 15]
 [33 42]]
[[14 19]
 [29 40]]


In [11]:
# 矩阵的转置
A = np.array([[1,2,3], [4,5,6]])

print(A)

print("矩阵A的转置",A.T)

print("矩阵A的转置\n",np.transpose(A))

[[1 2 3]
 [4 5 6]]
矩阵A的转置 [[1 4]
 [2 5]
 [3 6]]
矩阵A的转置
 [[1 4]
 [2 5]
 [3 6]]


In [13]:
#反矩阵(A必须为方阵,即行列相等,且必须是非奇异方阵(即每一列或者行之间不可以相异于其他列或行)
A = np.array([[1,2,3], [4,5,6], [7,8,9]])
print("矩阵A \n",A)
print("A的反矩阵 \n",np.linalg.inv(A))

B = np.array([[1,2],[3,4]])
print("B的反矩阵 \n",np.linalg.inv(B))

矩阵A 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
A的反矩阵 
 [[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]
B的反矩阵 
 [[-2.   1. ]
 [ 1.5 -0.5]]


In [19]:
# 单位矩阵: 若A为非奇异矩阵,则A @ A的反矩阵 = 单位矩阵(I)。所谓的单位矩阵是指任一行不能为其他行的倍数或多行的组合,包括四则运算,矩阵的列
# 也必须符合相同的规则
A = np.array([[9,8],[7,6]])
print(A)
print("A - 单位矩阵 \n",np.around(A @ np.linalg.inv(A)))

B = np.around([[1,2,3],[4,5,6],[7,8,9]])
print("B - 非单位矩阵 \n",np.around(B @ np.linalg.inv(B)))

'''
    B为奇异矩阵,因为第一列为0,说明行列式存在线性相关
'''

[[9 8]
 [7 6]]
A - 单位矩阵 
 [[1. 0.]
 [0. 1.]]
B - 单位矩阵 
 [[ 0.  1. -0.]
 [ 0.  2. -1.]
 [ 0.  3.  2.]]


'\n    B为奇异矩阵,因为第二列 = 第三列 + 1\n'

In [22]:
# 联立方程求解
'''
    x + y = 16
    10x + 25 y = 250
'''
# 定义方程的A和B
A = np.array([[1,1],[10,25]])
B = np.array([16,250])
print('A = ', A)
print('\n')
print('B = ', B)
print(B.reshape(2,1))

#线性代数求解
print("\n 线性代数求解")
print(np.linalg.inv(A) @ B)

#直接求解
print("\n 直接求解")
print(np.linalg.solve(A,B))

A =  [[ 1  1]
 [10 25]]


B =  [ 16 250]
[[ 16]
 [250]]

 线性代数求解
[10.  6.]

 直接求解
[10.  6.]
