In [2]:
import numpy as np

#矩阵
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[6,5,4],[3,2,1]])

#矩阵加法
print(A+B)

#矩阵减法
print("\n 矩阵减法")
print(A-B)


[[7 7 7]
 [7 7 7]]

 矩阵减法
[[-5 -3 -1]
 [ 1  3  5]]


In [7]:
#矩阵乘除法
C = np.array([[1,2,4],
              [4,5,6]])
D = np.array([[9,8],
              [7,6],
              [5,4]
              ])

print("\n 矩阵乘法")
print(C@D)
# print(np.dot(C,D))
# print(np.matmul(C,D))
print("C@D =======  D@C")
print(D@C)


 矩阵乘法
[[ 43  36]
 [101  86]]
C@D 与D@C
[[41 58 84]
 [31 44 64]
 [21 30 44]]


In [9]:
#特殊矩阵
A = np.array([[1,2,3],[4,5,6]])

#矩阵的转置
print("矩阵转置方法1")
print(A.T)
#矩阵转置
print("矩阵转置方法2")
print(np.transpose(A))

矩阵转置方法1
[[1 4]
 [2 5]
 [3 6]]
矩阵转置方法2
[[1 4]
 [2 5]
 [3 6]]


In [10]:
#反矩阵,Row和Column必须相等,即方阵
A = np.array([[1,2,3],[4,5,6],[7,8,9]])

print("A的反矩阵")
print(np.linalg.inv(A))


A的反矩阵
[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]


In [17]:
#单位矩阵
A = np.array([[1,2],[3,4]])
print("单位矩阵")
print(np.eye(2))

#矩阵@反矩阵=单位矩阵,表示A为非奇异矩阵
print("A@A.inv = I")
print(A @ np.linalg.inv(A))

print("==========================================")
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("A@A.inv = I")
print(A @ np.linalg.inv(A))

单位矩阵
[[1. 0.]
 [0. 1.]]
A@A.inv = I
[[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]]
A@A.inv = I
[[ 0.   1.  -0.5]
 [ 0.   2.  -1. ]
 [ 0.   3.   2.5]]


In [20]:
print(np.zeros((7,7)))
print(np.ones((7,7)))

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [22]:
#求解方程组
'''
    x + y = 16
    10x + 25y = 250

    转化为矩阵
    AX = B
    A@np.linalg.inv(A) @ X = B @ np.linalg.inv(A)
    IX = B@np.linalg.inv(A)   # I为单位矩阵
    X = B@ np.linalg.inv(A)
'''
A = np.array([[1,1],[10,25]])
b = np.array([16,250])
#求解X矩阵
print(np.linalg.solve(A,b))

[10.  6.]


In [24]:
#矩阵的相关方法
A = np.array([[1,2,3],[4,5,6],[7,8,9]])

#矩阵求逆
print("矩阵求逆")
print(np.linalg.inv(A))

#矩阵的特征值和特征向量
'''

特征值：表示线性变换在特征向量方向上的缩放比例。
特征向量：表示在该方向上仅被缩放而不改变方向的向量。

'''
print("矩阵的特征值和特征向量")
eigenvalues, eigenvectors = np.linalg.eig(A)
print(eigenvalues)
print(eigenvectors)

#矩阵的行列式
'''
行列式是一个从方阵到实数的映射，具有以下特性：
几何意义：行列式的绝对值表示矩阵所代表的线性变换对空间的体积（或面积）的缩放比例。
代数意义：行列式用于判断矩阵是否可逆、求解线性方程组、计算特征值等。
'''
print("矩阵的行列式")
print(np.linalg.det(A))

#奇异值分解
'''
奇异值分解（SVD）是一种用于分解矩阵的数学方法，它将一个矩阵分解为三个矩阵的乘积：
U、S和VT，其中U和VT是正交矩阵，S是一个对角矩阵。

U是一个m * m的正交矩阵,其列向量被称为左奇异向量
Σ是一个m * n的对角矩阵,矩阵中的对角元素为矩阵A的奇异值,这些奇异值是非负数,并按降序排列
VT是n*n的正交矩阵,矩阵V的列向量被称为右奇异向量。


奇异值的个数等于矩阵A的秩,最多为min(m,n)
奇异值描述在矩阵在不同方向上的伸缩比例
'''
print("奇异值分解")
U,s,VT = np.linalg.svd(A)
print("U",U)
print("s",s)
print("VT",VT)

矩阵求逆
[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]
矩阵的特征值和特征向量
[ 1.61168440e+01 -1.11684397e+00 -3.38433605e-16]
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]
矩阵的行列式
-9.51619735392994e-16
奇异值分解
U [[-0.21483724  0.88723069  0.40824829]
 [-0.52058739  0.24964395 -0.81649658]
 [-0.82633754 -0.38794278  0.40824829]]
s [1.68481034e+01 1.06836951e+00 3.33475287e-16]
VT [[-0.47967118 -0.57236779 -0.66506441]
 [-0.77669099 -0.07568647  0.62531805]
 [-0.40824829  0.81649658 -0.40824829]]
