In [21]:
#张量运算
import tensorflow as tf

print(tf.__version__)

#检查是否有GPU
print(tf.config.list_physical_devices('GPU'))

#声明常数
a = tf.constant([[1,2,3,4]])
print(a)
print(a + 10)
print(a - 10)
print(a / 10)
print(a * 10)

print(a.numpy())
print("===========================================\n")
#转为负数
print(tf.negative(a))
print("===========================================\n")

#做加法

#两个数
print(tf.add(1,2))
#两个向量相加
print(tf.add([1,2],[3,4]))

#平方
print(tf.square(5))
print(tf.square([1,2,3]))
print("=================计算和========================\n")
print(tf.reduce_sum([1,2,3]))
print(tf.reduce_sum(tf.constant([1,2,3])))
print(tf.reduce_sum([[1,2,5],[3,4,5]]))


2.18.0
[]
tf.Tensor([[1 2 3 4]], shape=(1, 4), dtype=int32)
tf.Tensor([[11 12 13 14]], shape=(1, 4), dtype=int32)
tf.Tensor([[-9 -8 -7 -6]], shape=(1, 4), dtype=int32)
tf.Tensor([[0.1 0.2 0.3 0.4]], shape=(1, 4), dtype=float64)
tf.Tensor([[10 20 30 40]], shape=(1, 4), dtype=int32)
[[1 2 3 4]]

tf.Tensor([[-1 -2 -3 -4]], shape=(1, 4), dtype=int32)

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([4 6], shape=(2,), dtype=int32)
tf.Tensor(25, shape=(), dtype=int32)
tf.Tensor([1 4 9], shape=(3,), dtype=int32)
=================计算和========================

tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(20, shape=(), dtype=int32)


In [4]:
#
import tensorflow as tf

'''
    tensorflow中的常数放在CPU上(使用constant方法),其他的放在GPU上
'''
x1 = tf.constant([1,2,3],dtype=tf.float32)
print("x1 是否在GPU #0 上:",x1.device.endswith('GPU:0')) # false,分配到cpu上

#设定x为均匀分配乱数 3x3
x2 = tf.random.uniform([3,3])
print("x2 是否在GPU #0 上:",x2.device.endswith('GPU:0')) # 如果有显卡,true

#
x3 = x1 + x2
print("x3 是否在GPU #0 上:",x3.device.endswith('GPU:0')) # 如果有显卡,true

x1 是否在GPU #0 上: False
x2 是否在GPU #0 上: False
x3 是否在GPU #0 上: False


In [34]:
#指定CPU或者GPU
import tensorflow as tf
import time

print(tf.config.list_physical_devices('CPU'))

#计算10次的时间
def time_matnul(x):
    start = time.time()
    for _ in range(10):
        tf.matmul(x,x)
    result = time.time() - start
    print("{:0.2f}ms".format(result*1000))

#强制在cpu上计算
print("在CPU上计算")
with tf.device("CPU:0"):
    x = tf.random.uniform([1000,1000])
    time_matnul(x)

#在GPU上计算
if tf.config.list_physical_devices('GPU'):
    print("在GPU上计算")
    with tf.device("GPU:0"):
        x = tf.random.uniform([1000,1000])
        time_matnul(x)


[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]
在CPU上计算
56.85ms


In [40]:
#稀疏矩阵(Sparser Matrix)
import tensorflow as tf
import numpy as np
'''
    1   0   0   0
    0   0   2   0
    0   0   0   0

'''
sparser_tensor = tf.sparse.SparseTensor(indices=[[0,0],[1,2]],values=[1,2],dense_shape=[3,4])
#打印值
print(sparser_tensor)

#转为正常的矩阵格式
x = tf.sparse.to_dense(sparser_tensor,default_value=0)
print(x)
print(type(x))
print(x.numpy())




SparseTensor(indices=tf.Tensor(
[[0 0]
 [1 2]], shape=(2, 2), dtype=int64), values=tf.Tensor([1 2], shape=(2,), dtype=int32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))
tf.Tensor(
[[1 0 0 0]
 [0 0 2 0]
 [0 0 0 0]], shape=(3, 4), dtype=int32)
<class 'tensorflow.python.framework.ops.EagerTensor'>
[[1 0 0 0]
 [0 0 2 0]
 [0 0 0 0]]
2.0.2
