In [5]:
import math

'''
1.向量
'''
import numpy as np

#定义一维向量
v = np.array([1,2,3])

#向量的长度
print(np.linalg.norm(v))

#计算向量的方向--->夹角

#计算角度,通过反函数计算出弧度(360度与2π的转化)
print(math.degrees(math.acos(1/2)))

3.7416573867739413
60.00000000000001


In [8]:
'''
2.矩阵
'''
import numpy as np

v = np.arange(1,11).reshape(2,5)
print(v)
print(v.T)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]
